### ISSUE TITLE
دسته بندی بر حسب فرمت فایل ها label:question

### ISSUE THREAD

**Issue by matin1099** [persepolisdm/persepolis_lib#1]
سلام وقت بخیر؛ قصد دارم ازین کتابخونه برای ساخت یک دانلودمنیجر(بیشتر گذر از تحریم) بسازم که در بستر  Google Colab کار کند.

چون این اولین باری هست که برنامه مربوط به دانلود و  اینترنتاست؛ و بنده اصلا(و با تاکید بیشتر **اصلا**) دانشی در حوزه دانلود و دریافت فایل از اینترنت ندارم نیاز برای مسئله زیر دارم:
در هنگام دانلود برخی از فایل ها فرمت انها انتهای لینک هست ولی ۱-بعضی ها نیست(مثلا:` example.com/pic.jpg.php`)
۲- بعضی ها چند بار ریدایرکت میکند ا به لینک دانلود دسترسی پیدا کنیم.
با فاکتور گرفتن گستردگی فرمتهای مختلف برای حل این مشکل چه رهیافتی باید اتخاذ کنم؟

با آرزوی صلح

**Comment by alireza-amirsamimi** [comment]
سلام
از کتابخانه persepolis_lib استفاده کردید؟

**Comment by matin1099** [comment]
سلامی دوباره؛ بله.
در واقع، در حال آماده سازیش هستم. 
اما پایه اصلی (موتور دانلود) همین کتابخانه هست.

**Comment by alireza-amirsamimi** [comment]
درباره مورد اول:
قبل از فرآیند دانلود اصلی persepolis_lib تلاش می‌کنه از طریق گرفتن اطلاعات header اسم فایل و فرمت اون رو تشخیص بده. برای همین اگر در header اسم و فرمت مشخص شده باشه مشکلی نیست. ولی اگر از header مشخص نباشه مجبور هست با توجه به لینک دانلود اسم پیش‌فرضی برای دانلود فایل انتخاب کنه. چاره دیگری به نظرم نمی‌رسه.
اما اینکه بعد از دانلود فایل‌ها بر اساس فرمت دسته‌بندی بشن به عهده ابزار دانلود نیست. دانلود منجر باید این کار رو بکنه. به عبارتی persepolis_lib به عنوان یک ماژول فقط یک وظیفه داره. دانلود فایل. دسته بندی فایل بر اساس فرمت وظیفه دانلود منجر هست. در [دانلود منجر پرسپولیس](https://github.com/persepolisdm/persepolis/) ما این کار رو بعد از اتمام دانلود فایل انجام میدیم. دانلود که تمام میشه، فایل بر اساس فرمت انتقال پیدا می‌کنه.
درباره مورد دوم:
در کد نوشته شده برای ماژول python requests گزینه redirect برابر با True تعریف شده. یعنی در حالت معمول  نباید با redirect شدن لینک مشکلی داشته باشید.

**Comment by matin1099** [comment]
بسیار عالی.
در جریان هستم که این دسته بندی برعهده دانلود نیست. هموزور که گفتم هیچ دانشی راجع به برنامه نویسی اینترنت ندارم. این پاسخ شما کمک بزرگی میکند.

ممنونم از زحماتتون برای جامعه نرم افزار آزاد.

**Comment by alireza-amirsamimi** [comment]
خواهش میکنم. سلامت باشید. 
در این [فایل](https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/persepolis_lib_prime.py#L938) از پروژه دانلود منجر پرسپولیس یک متد با نام findDownloadPath وجود داره که بعد از اتمام دانلود فایل‌ها رو بر اساس فرمت دسته‌بندی می‌کنه. شاید بهتون ایده بده.
موفق باشید

**Comment by matin1099** [comment]
خدا خیرت بده مرد!!!
سه روزه دارم میگردم ایکستنشن فایل پیداکنم و دسته بندی کنم.
فدایی داری😘😘
